databases:
  - name: sms-db
    databaseName: sms
    user: sms_user
    plan: free

services:
  - type: web
    name: sms-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sms.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
