services:
  - type: web
    name: sms-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sms.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
