# Generated by Django 6.0.5 on 2026-05-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('marks', models.FloatField()),
                ('course', models.CharField(max_length=100)),
                ('admsnType', models.CharField(max_length=20)),
            ],
        ),
    ]
